trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Checkout@1
  displayName: 'Checkout code from version control'
  inputs:
    repository: 'self'
    branch: 'main'

- script: |
    chmod +x code/build.sh
    chmod +x code/run-tests.sh
  displayName: 'Set execute permissions for scripts'

- script: ./code/build.sh
  displayName: 'Run Build Script'

- script: ./code/run-tests.sh
  displayName: 'Run Test Script'

- task: DeleteFiles@1
  displayName: 'Clean workspace after build'
  inputs:
    sourceFolder: '$(Build.SourcesDirectory)'
    contents: '**/*'

- task: Bash@3
  condition: succeeded()
  displayName: 'Notify build and tests succeeded'
  inputs:
    targetType: 'inline'
    script: echo 'Build and tests succeeded.'

- task: Bash@3
  condition: failed()
  displayName: 'Notify build failed'
  inputs:
    targetType: 'inline'
    script: echo 'Build failed. Check the logs for details.'
