# Start from the Jenkins LTS image
FROM jenkins/jenkins:lts

# Switch to root user to install Python
USER root

# Install Python 3 and pip
RUN apt-get update && \
    apt-get install -y python3 python3-pip

# Switch back to the Jenkins user
USER jenkins

# Expose port 8080
EXPOSE 8080
